copy /Y tstscn.bat ..\..\djgpp\misc\tstscn.bat
copy /Y tstscn.bat ..\..\symantec\misc\tstscn.bat
copy /Y tstscn.bat ..\..\turboc30\misc\tstscn.bat
copy /Y tstscn.bat ..\..\vc6\misc\tstscn.bat
copy /Y tstscn.bat ..\..\vs05\misc\tstscn.bat
copy /Y tstscn.bat ..\..\vs10\misc\tstscn.bat
copy /Y tstscn.bat ..\..\vs13\misc\tstscn.bat
copy /Y tstscn.bat ..\..\vs15\misc\tstscn.bat
copy /Y tstscn.bat ..\..\vs19\misc\tstscn.bat
copy /Y tstscn.bat ..\..\vs22\misc\tstscn.bat
